on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - name: checkout
        uses: actions/checkout@v2 # $GITHUB_WORKSPACE  is a temp variable
      - name: npm install
        uses: Npm@1
      - name: Hello world action step
        id: hello
        # instead of giving a public action we will give the action that we just created
        # uses: actions/javascript-actions@v1
        uses: ./
        with:
          who-to-greet: "rahul"
      # use output from the hello step
      - name: get the output time
        run: echo "the time was ${{ steps.hello.outputs.time }}"
